import type { RegionCode } from "~/types/search-options";

type RegionDefinition = readonly [label: string, code: RegionCode];

export const REGION_DEFINITIONS: readonly RegionDefinition[] = [
  ["Afeganistão", "AF"],
  ["África do Sul", "ZA"],
  ["Albânia", "AL"],
  ["Alemanha", "DE"],
  ["Andorra", "AD"],
  ["Angola", "AO"],
  ["Anguilla", "AI"],
  ["Antártida", "AQ"],
  ["Antígua e Barbuda", "AG"],
  ["Arábia Saudita", "SA"],
  ["Argélia", "DZ"],
  ["Argentina", "AR"],
  ["Armênia", "AM"],
  ["Aruba", "AW"],
  ["Austrália", "AU"],
  ["Áustria", "AT"],
  ["Azerbaijão", "AZ"],
  ["Bahamas", "BS"],
  ["Bahrein", "BH"],
  ["Bangladesh", "BD"],
  ["Barbados", "BB"],
  ["Bélgica", "BE"],
  ["Belize", "BZ"],
  ["Benin", "BJ"],
  ["Bermudas", "BM"],
  ["Bielorrússia", "BY"],
  ["Bolívia", "BO"],
  ["Bósnia e Herzegovina", "BA"],
  ["Botsuana", "BW"],
  ["Brasil", "BR"],
  ["Brunei", "BN"],
  ["Bulgária", "BG"],
  ["Burkina Faso", "BF"],
  ["Burundi", "BI"],
  ["Butão", "BT"],
  ["Cabo Verde", "CV"],
  ["Camarões", "CM"],
  ["Camboja", "KH"],
  ["Canadá", "CA"],
  ["Catar", "QA"],
  ["Cazaquistão", "KZ"],
  ["Chade", "TD"],
  ["Chile", "CL"],
  ["China", "CN"],
  ["Chipre", "CY"],
  ["Colômbia", "CO"],
  ["Comores", "KM"],
  ["Coreia do Norte", "KP"],
  ["Coreia do Sul", "KR"],
  ["Costa do Marfim", "CI"],
  ["Costa Rica", "CR"],
  ["Croácia", "HR"],
  ["Cuba", "CU"],
  ["Curaçao", "CW"],
  ["Dinamarca", "DK"],
  ["Djibuti", "DJ"],
  ["Dominica", "DM"],
  ["Egito", "EG"],
  ["El Salvador", "SV"],
  ["Emirados Árabes Unidos", "AE"],
  ["Equador", "EC"],
  ["Eritreia", "ER"],
  ["Eslováquia", "SK"],
  ["Eslovênia", "SI"],
  ["Espanha", "ES"],
  ["Estados Unidos", "US"],
  ["Estônia", "EE"],
  ["Etiópia", "ET"],
  ["Fiji", "FJ"],
  ["Filipinas", "PH"],
  ["Finlândia", "FI"],
  ["França", "FR"],
  ["Gabão", "GA"],
  ["Gâmbia", "GM"],
  ["Gana", "GH"],
  ["Geórgia", "GE"],
  ["Gibraltar", "GI"],
  ["Granada", "GD"],
  ["Grécia", "GR"],
  ["Groenlândia", "GL"],
  ["Guadalupe", "GP"],
  ["Guam", "GU"],
  ["Guatemala", "GT"],
  ["Guernsey", "GG"],
  ["Guiana", "GY"],
  ["Guiana Francesa", "GF"],
  ["Guiné", "GN"],
  ["Guiné Equatorial", "GQ"],
  ["Guiné-Bissau", "GW"],
  ["Haiti", "HT"],
  ["Honduras", "HN"],
  ["Hong Kong", "HK"],
  ["Hungria", "HU"],
  ["Ilha Bouvet", "BV"],
  ["Ilha Christmas", "CX"],
  ["Ilha de Man", "IM"],
  ["Ilha Norfolk", "NF"],
  ["Ilhas Aland", "AX"],
  ["Ilhas Cayman", "KY"],
  ["Ilhas Cocos (Keeling)", "CC"],
  ["Ilhas Cook", "CK"],
  ["Ilhas Faroé", "FO"],
  ["Ilhas Geórgia do Sul e Sandwich do Sul", "GS"],
  ["Ilhas Heard e McDonald", "HM"],
  ["Ilhas Malvinas", "FK"],
  ["Ilhas Marianas do Norte", "MP"],
  ["Ilhas Marshall", "MH"],
  ["Ilhas Menores Distantes dos EUA", "UM"],
  ["Ilhas Salomão", "SB"],
  ["Ilhas Turks e Caicos", "TC"],
  ["Ilhas Virgens Britânicas", "VG"],
  ["Ilhas Virgens dos EUA", "VI"],
  ["Índia", "IN"],
  ["Indonésia", "ID"],
  ["Irã", "IR"],
  ["Iraque", "IQ"],
  ["Irlanda", "IE"],
  ["Islândia", "IS"],
  ["Israel", "IL"],
  ["Itália", "IT"],
  ["Jamaica", "JM"],
  ["Japão", "JP"],
  ["Jersey", "JE"],
  ["Jordânia", "JO"],
  ["Kiribati", "KI"],
  ["Kuwait", "KW"],
  ["Laos", "LA"],
  ["Lesoto", "LS"],
  ["Letônia", "LV"],
  ["Líbano", "LB"],
  ["Libéria", "LR"],
  ["Líbia", "LY"],
  ["Liechtenstein", "LI"],
  ["Lituânia", "LT"],
  ["Luxemburgo", "LU"],
  ["Macau", "MO"],
  ["Macedônia do Norte", "MK"],
  ["Madagascar", "MG"],
  ["Malásia", "MY"],
  ["Malaui", "MW"],
  ["Maldivas", "MV"],
  ["Mali", "ML"],
  ["Malta", "MT"],
  ["Marrocos", "MA"],
  ["Martinica", "MQ"],
  ["Maurício", "MU"],
  ["Mauritânia", "MR"],
  ["Mayotte", "YT"],
  ["México", "MX"],
  ["Mianmar (Birmânia)", "MM"],
  ["Micronésia", "FM"],
  ["Moçambique", "MZ"],
  ["Moldávia", "MD"],
  ["Mônaco", "MC"],
  ["Mongólia", "MN"],
  ["Montenegro", "ME"],
  ["Montserrat", "MS"],
  ["Namíbia", "NA"],
  ["Nauru", "NR"],
  ["Nepal", "NP"],
  ["Nicarágua", "NI"],
  ["Níger", "NE"],
  ["Nigéria", "NG"],
  ["Niue", "NU"],
  ["Noruega", "NO"],
  ["Nova Caledônia", "NC"],
  ["Nova Zelândia", "NZ"],
  ["Omã", "OM"],
  ["Países Baixos", "NL"],
  ["Palau", "PW"],
  ["Palestina", "PS"],
  ["Panamá", "PA"],
  ["Papua-Nova Guiné", "PG"],
  ["Paquistão", "PK"],
  ["Paraguai", "PY"],
  ["Peru", "PE"],
  ["Polinésia Francesa", "PF"],
  ["Polônia", "PL"],
  ["Porto Rico", "PR"],
  ["Portugal", "PT"],
  ["Quênia", "KE"],
  ["Quirguistão", "KG"],
  ["Reino Unido", "GB"],
  ["República Centro-Africana", "CF"],
  ["República Congo-Brazzaville", "CG"],
  ["República Congo-Kinshasa", "CD"],
  ["República Dominicana", "DO"],
  ["República Tcheca", "CZ"],
  ["Reunião", "RE"],
  ["Romênia", "RO"],
  ["Ruanda", "RW"],
  ["Rússia", "RU"],
  ["Saara Ocidental", "EH"],
  ["Samoa", "WS"],
  ["Samoa Americana", "AS"],
  ["San Marino", "SM"],
  ["Santa Helena", "SH"],
  ["Santa Lúcia", "LC"],
  ["São Bartolomeu", "BL"],
  ["São Cristóvão e Névis", "KN"],
  ["São Martinho (França)", "MF"],
  ["São Martinho (Países Baixos)", "SX"],
  ["São Pedro e Miquelão", "PM"],
  ["São Tomé e Príncipe", "ST"],
  ["São Vicente e Granadinas", "VC"],
  ["Senegal", "SN"],
  ["Serra Leoa", "SL"],
  ["Sérvia", "RS"],
  ["Seychelles", "SC"],
  ["Singapura", "SG"],
  ["Síria", "SY"],
  ["Somália", "SO"],
  ["Sri Lanka", "LK"],
  ["Suazilândia", "SZ"],
  ["Sudão", "SD"],
  ["Sudão do Sul", "SS"],
  ["Suécia", "SE"],
  ["Suíça", "CH"],
  ["Suriname", "SR"],
  ["Svalbard e Jan Mayen", "SJ"],
  ["Tailândia", "TH"],
  ["Taiwan", "TW"],
  ["Tajiquistão", "TJ"],
  ["Tanzânia", "TZ"],
  ["Território Britânico do Oceano Índico", "IO"],
  ["Territórios Franceses do Sul", "TF"],
  ["Timor-Leste", "TL"],
  ["Togo", "TG"],
  ["Tokelau", "TK"],
  ["Tonga", "TO"],
  ["Trinidad e Tobago", "TT"],
  ["Tunísia", "TN"],
  ["Turcomenistão", "TM"],
  ["Turquia", "TR"],
  ["Tuvalu", "TV"],
  ["Ucrânia", "UA"],
  ["Uganda", "UG"],
  ["Uruguai", "UY"],
  ["Uzbequistão", "UZ"],
  ["Vanuatu", "VU"],
  ["Vaticano", "VA"],
  ["Venezuela", "VE"],
  ["Vietnã", "VN"],
  ["Wallis e Futuna", "WF"],
  ["Zâmbia", "ZM"],
  ["Zimbábue", "ZW"],
] as const;

export type RegionDefinitionCodes = (typeof REGION_DEFINITIONS)[number][1];
